# Dependencies
markdown:         kramdown
highlighter:      pygments  

# Permalinks
permalink:        pretty

# Setup
title:            Crash Test Astronomer
tagline:          'Creating things and talking about it'
description:      'Musings from a lifelong student'
production_url:              http://ezietsman.github.io
baseurl:          /

author:
  name:           'Ewald Zietsman'
  url:            http://ezietsman.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

